baseURL = "https://pensive-newton-6b1a8f.netlify.com"
languageCode = "en-us"
canonifyurls = true
paginate = 10
title = "Ewa Wipszycka seminar"
theme = "startbootstrap-clean-blog"

[author]
name = "Marta Szada"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "The seminar gathers a group of historians, archaeologists, historians of Roman law, epigraphists, and classicists sharing interest in Late Antiquity."
  Author = "Marta Szada"
  postSummariesFrontPage = 3 #Number of post summaries to show on front page, comment out to allow default(4)
  
  [[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
